#ifndef INCLUDE_SYSCALLS_H
#define INCLUDE_SYSCALLS_H

#include "../INTERRUPTS/interrupt.h"

#define SYSCALL_INTERRUPT_VECTOR 128

#define SYSCALL_EXIT 1
#define SYSCALL_READ 3
#define SYSCALL_WRITE 4
#define SYSCALL_OPEN 5
#define SYSCALL_CLOSE 6
#define SYSCALL_LSEEK 19
#define SYSCALL_GETPID 20
#define SYSCALL_DUP 41
#define SYSCALL_DUP2 63
#define SYSCALL_FTRUNCATE 93
#define SYSCALL_FSTAT 108

#define SYSCALL_FS_CREATE 450
#define SYSCALL_FS_WRITE 451
#define SYSCALL_FS_READ 452
#define SYSCALL_FS_MKDIR 453
#define SYSCALL_FS_LIST 454
#define SYSCALL_FS_UNLINK 455
#define SYSCALL_FS_RMDIR 456
#define SYSCALL_FS_STAT 457
#define SYSCALL_FS_RENAME 458
#define SYSCALL_FS_TRUNCATE 459
#define SYSCALL_FS_CHMOD 460

int syscall_dispatch(struct cpu_state *cpu);

#endif
